development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:5643a73ae1fda751bd6dd740807fa4e2@soldierfish.redistogo.com:9371/
  channel_prefix: women_in_comedy_api_production
